.\" Manpage for cppmounts
.TH man 3 "29 April 2012" "1.0" "cppmounts man page"
.SH NAME
cppmounts \- an open source C++ library to list mac or linux mounts
.SH DESCRIPTION
cppmounts is an open source C++ library to list mac or linux mounts using an easy to use interface.

.SH FILES
The header files are located in {headerdir} directory.

The library is available both as shared object and static library:
.IP
{libdir}/lib{PRODUCT_NAME}.a
.br
{libdir}/lib{PRODUCT_NAME}.so

.SH AUTHOR
Geoffroy Planquart (geoffroy@aethelflaed.com)
